### ISSUE TITLE
Heroku Deployment Fails

### ISSUE THREAD

**Issue by kmontenegro** [casefoundation/weekly-roundup#1]
One-click deployment to Heroku failed with:
"Node version not specified in package.json"

bcrypt also seems to have been a contributing factor to the failed install.

Log file attached...and thanks for creating this: it looks good! Excited to get it working.
[roundup-heroku-log.txt](https://github.com/casefoundation/weekly-roundup/files/3586978/roundup-heroku-log.txt)

**Comment by johnjones4** [comment]
@kmontenegro it should be all set to go now! I was able to recreate the issue, and made some updates to address it. I was then able to successfully deploy to Heroku.

Please reach out if you have additional issues, and if you end up using this project, let us know! We love to see our work in use!

**Comment by kmontenegro** [comment]
Excellent! It deployed as expected once those two pieces were addressed. Thank you.
